apiVersion: v1
kind: Service
metadata:
  name: {{ template "cassandra.fullname" . }}
  labels:
    app: {{ template "cassandra.name" . }}
    chart: {{ template "cassandra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
{{- if eq .Values.service.type "LoadBalancer" }} {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }} {{- end }}
  type: {{ .Values.service.type }}
  ports:
  - name: cql
    port: {{ .Values.service.port }}
    targetPort: cql
    {{- if (and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.cql)))}}
    nodePort: {{ .Values.service.nodePorts.cql }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
{{- if .Values.cluster.enableRPC }}
  - name: thrift
    port: {{ .Values.service.thriftPort }}
    targetPort: thrift
    {{- if (and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.thrift)))}}
    nodePort: {{ .Values.service.nodePorts.thrift }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
{{- end }}
  selector:
    app: {{ template "cassandra.name" . }}
    release: {{ .Release.Name }}
