{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "shortenurl.serviceAccountName" . }}
  labels:
{{ include "shortenurl.labels" . | indent 4 }}
{{- end -}}
